// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB52dn12ZSVWhflSPvqnu1S-Kz6pf8-Z_g',
    appId: '1:166875423618:web:86657dd722f9607e21259b',
    messagingSenderId: '166875423618',
    projectId: 'aula-02-24',
    authDomain: 'aula-02-24.firebaseapp.com',
    storageBucket: 'aula-02-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8eiUiFXRrD03zrgDV_GUg0KATNs6wHQE',
    appId: '1:166875423618:android:ba06ad26f2d7c64321259b',
    messagingSenderId: '166875423618',
    projectId: 'aula-02-24',
    storageBucket: 'aula-02-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADtovyTlHMP81OtU4S4inlfoYcFNcbVlU',
    appId: '1:166875423618:ios:c94a63ea7ff96c3821259b',
    messagingSenderId: '166875423618',
    projectId: 'aula-02-24',
    storageBucket: 'aula-02-24.appspot.com',
    iosBundleId: 'com.example.aulaFirebase',
  );
}
